# Site settings
title:          Sky's blog
description:    "这是我的个人博客"
#baseurl:        ""
url:            "https://sky-wei.github.io"

# Author
author:
  name:         sky
  url:          "https://github.com/sky-wei"
  email:        "jingcai.wei@163.com"

# Theme
remote_theme: chesterhow/tale

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate
  - jekyll-remote-theme
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
